[package]
name = "wayplover"
descritpion = "Steno Stoke Interperter"
version = "0.1.1"
license = "MIT OR Apache-2.0"
edition = "2018"
homepage = "https://www.github.com/Travisdavis-ops/wayplover"
repository = "https://www.github.com/Travisdavis-ops/wayplover"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
json = "0.12.4"
tui = "0.15"
termion = "1.5"
clap = "2.33.3"
evdev = "0.11.0"
