[package]
name = "wayplover"
descritpion = "Steno Stoke Interperter"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
json = "0.12.4"
tui = "0.15"
termion = "1.5"
clap = "2.33.3"
evdev = {git="https://github.com/emberian/evdev.git", branch="master"}
