name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v1
      with:
        packages: rustup, alsaLib, alsaTools, alsaUtils, speechd, glibc
        script: |
          rustup default stable
          cargo build --all-features
